### ISSUE TITLE
Types "decimal" mal paramétrés dans le script SQL

### ISSUE THREAD

**Issue by jframiara** [ThomasLandes/FREDI#3]
Dans le script SQL, les types "decimal" ne contiennent pas le nombre de décimales. Ca équivaut à des entiers, ce qui est embêtant pour les montants financiers.
Par exemple "decimal(10,2) signifie dix chiffres dont deux après la virgule.

**Comment by Simoniaque** [comment]
Tous les types "decimal" ont été remplacé par "float"
